services:
  - type: web
    name: solace-backend
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements_prod.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app --bind 0.0.0.0:$PORT -w 2

    envVars:
      - key: SECRET_KEY
        value: "replace-this-with-a-long-random-string"
      - key: PYTHON_VERSION
        value: "3.10"